# Generated by Django 3.1.7 on 2021-03-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dakhlokharj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dakhlokharj',
            name='date',
            field=models.CharField(blank=True, default='1400/1/7 18:24:16', max_length=50),
        ),
    ]
