# Generated by Django 3.1.7 on 2021-03-28 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dakhlokharj', '0002_auto_20210327_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dakhlokharj',
            name='date',
            field=models.CharField(blank=True, default=datetime.datetime(2021, 3, 28, 16, 22, 46, 931816, tzinfo=utc), max_length=50, null=True),
        ),
    ]
