# Generated by Django 3.1.7 on 2021-03-28 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dakhlokharj', '0003_auto_20210328_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dakhlokharj',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 28, 16, 23, 25, 521704, tzinfo=utc), null=True),
        ),
    ]
