# Generated by Django 3.1.7 on 2021-03-28 16:32

from django.db import migrations, models
import extensions.jalaliconverter


class Migration(migrations.Migration):

    dependencies = [
        ('dakhlokharj', '0004_auto_20210328_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dakhlokharj',
            name='date',
            field=models.CharField(blank=True, default=extensions.jalaliconverter.mydate, max_length=50, null=True),
        ),
    ]
