# Generated by Django 3.1.7 on 2021-03-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dakhlokharj', '0005_auto_20210328_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dakhlokharj',
            name='amount',
            field=models.FloatField(),
        ),
    ]
